//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int ExpensesKey { get; set; }
        public string UserEmail { get; set; }
        public string KindOfExpenses { get; set; }
        public string ExpensesTitle { get; set; }
        public int PricePerOne { get; set; }
        public int NumberOfRepeatExpenses { get; set; }
        public int TotalPriceToPay { get; set; }
    }
}
