//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Feedback()
        {
            this.SelectedBies = new HashSet<SelectedBy>();
        }
    
        public int FeedbackKey { get; set; }
        public string KindOfFeedback { get; set; }
        public string FeedbackDescription { get; set; }
        public Nullable<float> FeedbackLongitude { get; set; }
        public Nullable<float> FeedbackLatitude { get; set; }
        public string FeedbackCountry { get; set; }
        public string FeedbackRegionOfTheCountry { get; set; }
        public string FeedbackTitle { get; set; }
        public string FeedbackPhoto { get; set; }
        public string FeedbackPersona { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelectedBy> SelectedBies { get; set; }
    }
}
