//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SleepingComplex
    {
        public int SleepingComplexesKey { get; set; }
        public int OptionsKey { get; set; }
        public int SleepingComplexesCost { get; set; }
        public int NumberOfNightsSleepingComplexes { get; set; }
        public string SleepingComplexesName { get; set; }
        public string SleepingComplexesLocationCountry { get; set; }
        public string SleepingComplexesRegionOfTheCountry { get; set; }
        public Nullable<float> SleepingComplexesLongitude { get; set; }
        public Nullable<float> SleepingComplexesLatitude { get; set; }
        public Nullable<float> SleepingComplexesFinallandmark { get; set; }
        public string SleepingComplexesPersona { get; set; }
        public string SleepingComplexesDescription { get; set; }
        public string SleepingComplexesPhoto { get; set; }
    
        public virtual Option Option { get; set; }
    }
}
