//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int TripsKey { get; set; }
        public int OptionsKey { get; set; }
        public string KindOfTrips { get; set; }
        public int TripsTimeInMinutes { get; set; }
        public int TripsCost { get; set; }
        public int NumberOfRepeatTrips { get; set; }
        public string TripsName { get; set; }
        public string TripsLocationCountry { get; set; }
        public string TripsRegionOfTheCountry { get; set; }
        public Nullable<float> TripsLongitude { get; set; }
        public Nullable<float> TripsLatitude { get; set; }
        public Nullable<float> TripsFinallandmark { get; set; }
        public string TripsPersona { get; set; }
        public string TripsDescription { get; set; }
        public string TripsPhoto { get; set; }
    
        public virtual Option Option { get; set; }
    }
}
