//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attraction
    {
        public int AttractionsKey { get; set; }
        public int OptionsKey { get; set; }
        public string KindOfAttraction { get; set; }
        public int AttractionsTimeInMinutes { get; set; }
        public int AttractionsCost { get; set; }
        public int NumberOfRepeatAttractions { get; set; }
        public string AttractionsName { get; set; }
        public string AttractionsLocationCountry { get; set; }
        public string AttractionsRegionOfTheCountry { get; set; }
        public Nullable<float> AttractionsLongitude { get; set; }
        public Nullable<float> AttractionsLatitude { get; set; }
        public Nullable<float> AttractionsFinallandmark { get; set; }
        public string AttractionsPersona { get; set; }
        public string AttractionDescription { get; set; }
        public string AttractionPhoto { get; set; }
    
        public virtual Option Option { get; set; }
    }
}
