//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForFevPerUser
    {
        public int Fkey { get; set; }
        public string Fname { get; set; }
        public string Fcontry { get; set; }
        public Nullable<float> Flat { get; set; }
        public Nullable<float> Flot { get; set; }
        public string Fdescription { get; set; }
        public string Fphoto { get; set; }
        public string Fuseremail { get; set; }
    }
}
