//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class igroup199_prodEntities : DbContext
    {
        public igroup199_prodEntities()
            : base("name=igroup199_prodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AidComplex> AidComplexes { get; set; }
        public virtual DbSet<Attraction> Attractions { get; set; }
        public virtual DbSet<Chapter> Chapters { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Expens> Expenses { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<ForFevPerUser> ForFevPerUsers { get; set; }
        public virtual DbSet<Option> Options { get; set; }
        public virtual DbSet<RegionOfTheCountry> RegionOfTheCountries { get; set; }
        public virtual DbSet<SelectedBy> SelectedBies { get; set; }
        public virtual DbSet<SleepingComplex> SleepingComplexes { get; set; }
        public virtual DbSet<TalkWith> TalkWiths { get; set; }
        public virtual DbSet<TravelDiary> TravelDiaries { get; set; }
        public virtual DbSet<Trip> Trips { get; set; }
        public virtual DbSet<UserFavourite> UserFavourites { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
