//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelectedBy
    {
        public int OptionsKey { get; set; }
        public int FeedbackKey { get; set; }
        public string UserEmail { get; set; }
        public string CountryName { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Feedback Feedback { get; set; }
        public virtual Option Option { get; set; }
        public virtual User User { get; set; }
    }
}
